<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>CertificateVerification.Web</RootNamespace>
    <AssemblyName>CertificateVerification.Web</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>
</Project>
